### ISSUE TITLE
Is there a possibility to use access token instead of JSON file for authentication?

### ISSUE THREAD

**Issue by zaidanr** [carlospolop/bf_my_gcp_permissions#1]
Is there a possibility of using an access token (from `gcloud auth print-access-token`) instead of a JSON file for authentication?  If so, could you provide a brief overview of the process and I'll try to build and make a PR. Thanks

**Comment by carlospolop** [comment]
Yes, there is! But I cannot give you an exact way to do it as I haven't look into it yet.
The only help I can give you is that gcloud uses a token this way: 
![image](https://user-images.githubusercontent.com/17181413/217812077-56d1d756-88bd-4425-97f9-64a1da0cb079.png)

So I guess you could check `gcloud` code to see how is it using it, or investigate more options for the object `service_account.Credentials` that allows to use just the token as credentials.

Feel free to send a PR!

**Comment by carlospolop** [comment]
hi @zaidanr this was added in the last commit
